dist: bionic
language: generic
services:
- docker
env:
  global:
  - secure: G2JvawRg/XHkDHCTBzfAuWtdpD3QkrgrUNIp+re4WbC/msHlff8xmzx8HV3+LPJaYRHFgVHKWEwIYB84AW+uedgQ8qIFXJXn/eFsVEn6sXqpPTdAuKN/OVaP93Qa7Ot6a7DcFWoHenbn+dxeVtXQTuH06meHWzKbqNGuXnd6NTWPX8SXGlrc65zngvdTucCPE/O0Uy47xvKcwCaZKz/73BDbFXUuEel1pNZCVvXYPP8/BsFKVb7W6D0jxkBv5YkurogomXZkzsxhBYkp42VFS0rOgS+IwDhpP8JBYGbQhyXCWczAO909z79y9Q6vgRckjVkzrp/PYf3IhQpNoLFrLKAMWAl+aiRHFWOOotcWaIIz8o6C/nkAr9Z5XZTMubFfVeRWz3MSw7NeRnJka5A8Et8MHbPcLl0a3pP6BbkTPyQ/hiNgOhhwF3KzOU7q9oDy2uvKuyS2dmQQVU6BYrVg+cmWBwri5sdJG281ofZH+xvkHr6w75QA1npVU8SmxSOa2I4+WZQWItkv5kzHJQ5vG1Z0OEKxV3hzxY2NpdoZb8HBSSKD+6WteGFXDmGOYjuxCOLQj2i+MrmxNTIFaWWPYluYOCrVmETW/Lnf+7i4m2VVO6CItInomoJMVo9Y24b0FCub/PLK94thCUzYeFVa4fOhX0l6RgiG/8NAF2gYE6s=
  - secure: RONPcdhLRx3IA9TdRMG1ZGB6Rz32QQDbG8/P6dI6Filw06KSzmkbZkpuEzCD1BJrms1XnEuNm5d1WxTPGQdk2861kVsAt8VFtmorEnoS3fHVCMzRJU6dSA21fAmIb7So/Tgn+nQjoFYau1JQomaZErtDltLF4aWpPTGuPM7YJ8EQbZYq86Fx+0bUkxpmkC3QGyC1YGINHFdD3TUqcsDAdRI5V7HZIkVCvDiKS8acvQdOnFcqbyKk6bAQ4g/gw+WB09uv2QwuUDX0g+RsS3OCmNZIhS9d11EYAHzzpi1A2FUtbOEb2/dc7uvB6Dh7+L5StaLNh8EfcA4yjGfCGobX8LCMe69MI2WjxEW8f6QoUzKi8NQhw2Lxk4YhMOo/lEAGrFf1AstInN7cWR2/j/spVv5mn7q4cCEl16aztjKUpCBkI6bkLPsLYFV5p7h7OvctpAs/sebkC+8FYt+nb29AFO0Q8d4PCpo6ypnoNLXDPgzzd35S+HiArGO03Mgh+D6YzmeCeM9BKAJQQcLDWY8nleDigDJihMZABsK8BX4wRjcdubYs2eBIKlMBh/sLzd5Igdk1jpyD1QD/gCs8Vkz96MDK6RE1HJLhQVXidIYIzYrVIQndW9tz0upKuLfftSnL33YoDeYAH5gof1RuKj+6sJPvRwTM4UIjsAkJWkI168s=
  
script: make
after_success:
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- make release
- fi
